#! /bin/bash

total=$(free -h | awk '/^Mem:/{print $2}')
used=$(free -h | awk '/^Mem:/{print $3}')

total_number=${total::-1}
used_number=${used::-1}

percentage=$(echo "scale=1;($used_number/$total_number)*100" | bc)

echo "$percentage% ($used/$total)"